#!/bin/bash
# svn-to-git
# Created Mon Jun 13 14:47:05 AKDT 2016
# Copyright (C) 2016 by Raymond E. Marcil <marcilr@gmail.com>
#
# Converted svn repository to git.
#

# =================================================
# Configuration
# =================================================

#
# Enable/disable debugging.
#
DEBUG=true

TMPDIR=/tmp/${0}

# Configure svn and git base directories
SVNROOT=/data/svnroot
GITROOT=/data/git


# =================================================
# Binaries
# =================================================
BASENAME=/usr/bin/basename


# =================================================
# Functions
# =================================================

#
# debug()
# Output debugging text.
# INPUT: $1 - Text to output if DEBUG="
#
function debug {

  if [ ${DEBUG} = "true" ]; then
    echo "debug() ${1}"
  fi

}


#
# message()
# Display specified message passed as argument.
#
# INPUT
# =====
# Message to display as argument.
#
# RESULTS
# =======
# Displays argument to stdio.
#
function message {

  echo ${1}

}


#
# usage()
# Display usage and exit.
#
function usage(){
  message "Usage: ${0} <svn> <git>"
  message "   -d | --debug   Enable debugging."
  message "   -h | --help    Create non-hierarchical repository."
  message "  <svn>           Local subversion repository path."
  message "                  Like: /data/svnroot/tex/wrt54gl/wrt54gl/"
  message "  <git>           Local git repository path."
  message "                  Like: /data/git/tex/wrt54gl/"
}



# =================================================
# Main
# =================================================

BASE=`${BASENAME} "${0}"`

TMPDIR="/tmp/${BASE}"

debug "TMPDIR: ${TMPDIR}"
